### ISSUE TITLE
Structural variants in VCF4.4 meta-issue

### ISSUE THREAD

**Issue by tskir** [samtools/hts-specs#544]
# A suite of @d-cameron's PRs
* [x] https://github.com/samtools/hts-specs/pull/465 Improved Structural Variant Support
* [x] https://github.com/samtools/hts-specs/pull/468 Allow multiple SVs per record (housekeeping changes to ensure all SV fields allow for multiple SV allels)
* [x] https://github.com/samtools/hts-specs/pull/469 EVENT/EVENTTYPE for SV classification (grouping SVs into higher-order events)
* [x] https://github.com/samtools/hts-specs/pull/517 Added SVCLAIM field (making CN/BP clarification explicit)
* [x] https://github.com/samtools/hts-specs/pull/553 Deprecate SVTYPE

**Comment by tskir** [comment]
A suite of @d-cameron's PRs has been reviewed 2021-02-22...2021-02-25. (Apologies for not quite meeting the deadline!)

After these are rebased and comments are addressed, we can merge them into the draft and then continue working from it.

**Comment by tskir** [comment]
Hi @d-cameron! Just wanted to send a gentle reminder about the four PRs awaiting action. Actually, if you find there's a lot on your hands right now, just let me know and I can go ahead and apply those changes myself—the remaining ones seem to be fairly incontroversial.

**Comment by d-cameron** [comment]
Sorry for the delay. Grant season just ended so I'll be able to get these done over the next week or two.

@tskir Do we have a offical location for test/validation files yet? It would make sense to include exemplar VCFs for the 4.4 changes but I'm not sure where I should put them.

**Comment by tskir** [comment]
Hi @d-cameron! No problem about the delay.

The locations for the test and example files will probably follow the conventions proposed in this PR: https://github.com/samtools/hts-specs/pull/491/files — it's not merged yet, but any further changes are unlikely.

And also, when including the example files, I'd like to suggest we make it a separate PR to avoid any delays in merging the existing ones.

**Comment by tskir** [comment]
Status update:
* #468, #517 already merged
* I agree with the [suggestion](https://github.com/samtools/hts-specs/pull/465#issuecomment-829345560) to split #465 into smaller PRs, to the degree possible
* I suggest merging #469 as is (resolving conflicts & rebaselining required), and address additional comments as follow-up PRs
* Left some technical comments for #553, conceptually agree with the changes
